### ISSUE TITLE
Augment or View Albumentations is not applying/displaying transformation samples

### ISSUE THREAD

**Issue by dokutoshi** [jacobmarks/fiftyone-albumentations-plugin#4]
Using most recent version:

Test Case: a custom dataset with object detection data and image classification, tried a few single transformations, including flip, blur, randomrotate etc. 

After applying the transformation on 3 samples and setting the number of augmentations per sample (1-3), there are not transformation viewable in the dataset.

Additionally, executed the `view_last_albumentations_run operator` command and there are no samples.

conda list

Version info:
# Name                    Version                   Build  Channel
libopencv                 4.9.0           headless_py311h18d748c_12    conda-forge
opencv                    4.9.0           headless_py311h5151cf2_12    conda-forge
opencv-python       4.9.0.80                 pypi_0    pypi
py-opencv                 4.9.0           headless_py311h7e6d3fa_12    conda-forge
numpy                     1.26.4                   pypi_0    pypi

(tf_2.12) (base) leopimentel@XRXC65LQ69s-MacBook-Pro% pip show fiftyone
Name: fiftyone
Version: 0.23.8
Summary: FiftyOne: the open-source tool for building high-quality datasets and computer vision models
Home-page: https://github.com/voxel51/fiftyone
Author: Voxel51, Inc.
Author-email: info@voxel

**Comment by jacobmarks** [comment]
Thanks for logging this @dokutoshi , the issue was due to something "clever" that was happening on the backend. Whenever the dataset was opened, the plugin was attempting to automatically clean up temporary files and augmentations. I'd still like to find a way to do this, but for now, this has been removed and replaced with a `cleanup_last_albumentations_run` operator which you can call.

To use the latest version of the plugin, the easiest option is through the UI. Install the "plugins" plugin, which is used to manage plugins (lol).

```bash
fiftyone plugins download \
    https://github.com/voxel51/fiftyone-plugins \
    --plugin-names @voxel51/plugins
```

Then use the install_plugin operator. Go to the community tab and select Albumentations plugin from the dropdown, and update.

Let me know if you are still running into issues, but closing this for now.

**Comment by dokutoshi** [comment]
Awesome!

Confirmed it works!
I prefer the latest update -  a separate delete control.
Allows the user to stack transformations in a ”creative” fashion.

Best,

Leo
Sent from my iPhone

> On May 8, 2024, at 04:37, Jacob Marks ***@***.***> wrote:
>
> To use the latest version of the
This email and any attachments may contain private, confidential and privileged material for the sole use of the intended recipient. Any review, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and delete this email and any attachments afterwards.
